/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerTeman;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelTeman;
import util.Koneksi;

/**
 *
 * @author Juli
 */
public class ViewTeman extends javax.swing.JPanel {
Koneksi koneksi = new Koneksi();
ModelTeman mote = new ModelTeman();
ControllerTeman conte = new ControllerTeman();
    /**
     * Creates new form ViewTeman
     */
    public ViewTeman() {
        initComponents();
        tampilTeman();
    }
  private void tampilTeman() {
        koneksi.koneksiDB();

        DefaultTableModel tabel = new DefaultTableModel();

        tabel.addColumn("ID");
        tabel.addColumn("Nama Teman");
        tabel.addColumn("Nomor Handphone");
        tabel.addColumn("Email");

        TabelTeman.setModel(tabel);
        try {
            String sql = "select * from tbl_teman";

            ResultSet res = koneksi.s.executeQuery(sql);
            while (res.next()) {
                tabel.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("nope"),
                    res.getString("email")
                });
                TabelTeman.setModel(tabel);

            }
        } catch (SQLException eer) {
            System.err.println("SQLException:" + eer.getMessage());
        }
    }

    private void tombolBaru() {
        txt_namaT.setEnabled(true);
        txt_nopeT.setEnabled(true);
        txt_emailT.setEnabled(true);
        txt_namaT.requestFocus();
        bersihTxtField();
    }

    private void tombolBatal() {
        txt_namaT.setEditable(false);
        txt_nopeT.setEditable(false);
        txt_emailT.setEditable(false);
        bersihTxtField();
        btn_simpanT.setEnabled(false);
        btn_baruT.setText("Baru");
    }
    
    private void bersihTxtField(){
        txt_idT.setText("");
        txt_namaT.setText("");
        txt_nopeT.setText("");
        txt_emailT.setText("");
    }
    
    private void tabelKlik(){
        btn_hapusT.setEnabled(true);
        btn_ubahT.setEnabled(true);
    }
    private void tabelUnKlik(){
        btn_hapusT.setEnabled(false);
        btn_ubahT.setEnabled(false);
        bersihTxtField();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_namaT = new javax.swing.JTextField();
        txt_idT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nopeT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_emailT = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btn_baruT = new javax.swing.JButton();
        btn_simpanT = new javax.swing.JButton();
        btn_bersihT = new javax.swing.JButton();
        btn_hapusT = new javax.swing.JButton();
        btn_ubahT = new javax.swing.JButton();
        btn_tutupT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelTeman = new javax.swing.JTable();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nama");

        txt_namaT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_namaT.setEnabled(false);

        txt_idT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_idT.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("No. Hp");

        txt_nopeT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_nopeT.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("E-mail");

        txt_emailT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_emailT.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        btn_baruT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_baruT.setText("Baru");
        btn_baruT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_baruTActionPerformed(evt);
            }
        });

        btn_simpanT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_simpanT.setText("Simpan");
        btn_simpanT.setEnabled(false);
        btn_simpanT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanTActionPerformed(evt);
            }
        });

        btn_bersihT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_bersihT.setText("Bersih");
        btn_bersihT.setEnabled(false);
        btn_bersihT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihTActionPerformed(evt);
            }
        });

        btn_hapusT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_hapusT.setText("Hapus");
        btn_hapusT.setEnabled(false);
        btn_hapusT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusTActionPerformed(evt);
            }
        });

        btn_ubahT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_ubahT.setText("Ubah");
        btn_ubahT.setEnabled(false);

        btn_tutupT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_tutupT.setText("Tutup");
        btn_tutupT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tutupTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_baruT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpanT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bersihT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ubahT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapusT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tutupT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ubahT)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapusT)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tutupT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_baruT)
                        .addGap(18, 18, 18)
                        .addComponent(btn_simpanT)
                        .addGap(18, 18, 18)
                        .addComponent(btn_bersihT)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabelTeman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelTeman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelTemanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelTeman);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_emailT, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_namaT, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nopeT, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_idT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_namaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nopeT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_emailT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_baruTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_baruTActionPerformed
        // TODO add your handling code here:
        String logic = btn_baruT.getText();
        if(logic.equals("Baru")){
            btn_simpanT.setEnabled(true);
            btn_baruT.setText("Batal");
            tombolBaru();
        }else{
            btn_simpanT.setEnabled(false);
            btn_baruT.setText("Baru");
            tombolBatal();
        }
    }//GEN-LAST:event_btn_baruTActionPerformed

    private void btn_simpanTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanTActionPerformed
        // TODO add your handling code here:
        String nama = txt_namaT.getText();
        String nope = txt_nopeT.getText();
        String email = txt_emailT.getText();
        if(nama.equals("")||nope.equals("")||email.equals("")){
            JOptionPane.showMessageDialog(null,"Harap isi Data dengan Benar");
        }else{
            if(JOptionPane.showConfirmDialog(null,"Yakin Ingin Menyimpan ? ","PERHATIAN",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                try{
                    mote.setNama(nama);
                    mote.setNope(nope);
                    mote.setEmail(email);
                    
                    conte.simpanDataTeman(mote);
                    tampilTeman();
                    tombolBatal();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Harap Isi Data Dengan Benar");
                }
            }
        }
    }                                           

    private void btn_ubahTActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Merubah ?","PERHATIAN",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try{
                int id = Integer.parseInt(txt_idT.getText());
                String nama = txt_namaT.getText();
                String nope = txt_nopeT.getText();
                String email = txt_emailT.getText();
                
                mote.setId(id);
                mote.setNama(nama);
                mote.setNope(nope);
                mote.setEmail(email);
                
                conte.ubahDataTeman(mote);
                tampilTeman();
                tabelUnKlik();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,""+e.getMessage());
            }
        }else{
            
        }
    }//GEN-LAST:event_btn_simpanTActionPerformed

    private void btn_hapusTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusTActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null,"Apakah Anda Ingin Menghapus ?","PERHATIAN",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            try{
                int id = Integer.parseInt(txt_idT.getText());
                mote.setId(id);
                conte.hapusTeman(mote);
                tampilTeman();
                tabelUnKlik();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, ""+e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_hapusTActionPerformed

    private void btn_bersihTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihTActionPerformed
        // TODO add your handling code here:
        bersihTxtField();
    }//GEN-LAST:event_btn_bersihTActionPerformed

    private void btn_tutupTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tutupTActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_tutupTActionPerformed

    private void TabelTemanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelTemanMouseClicked
        // TODO add your handling code here:
        try{
            int baris = TabelTeman.getSelectedRow();
            
            txt_idT.setText(TabelTeman.getValueAt(baris,0).toString());
            txt_namaT.setText(TabelTeman.getValueAt(baris,1).toString());
            txt_nopeT.setText(TabelTeman.getValueAt(baris,2).toString());
            txt_emailT.setText(TabelTeman.getValueAt(baris,3).toString());
            tabelKlik();
        }catch(Exception e){
            System.err.println(""+e.getMessage());
        }
    }//GEN-LAST:event_TabelTemanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelTeman;
    private javax.swing.JButton btn_baruT;
    private javax.swing.JButton btn_bersihT;
    private javax.swing.JButton btn_hapusT;
    private javax.swing.JButton btn_simpanT;
    private javax.swing.JButton btn_tutupT;
    private javax.swing.JButton btn_ubahT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_emailT;
    private javax.swing.JTextField txt_idT;
    private javax.swing.JTextField txt_namaT;
    private javax.swing.JTextField txt_nopeT;
    // End of variables declaration//GEN-END:variables
}
